# Generated by Django 5.0.6 on 2024-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
